# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/Documentos/MP_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/Documentos/MP_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documentos/MP_2/CMakeFiles /home/daniel/Documentos/MP_2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Documentos/MP_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testa_pilha

# Build rule for target.
testa_pilha: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testa_pilha
.PHONY : testa_pilha

# fast build rule for target.
testa_pilha/fast:
	$(MAKE) -f CMakeFiles/testa_pilha.dir/build.make CMakeFiles/testa_pilha.dir/build
.PHONY : testa_pilha/fast

#=============================================================================
# Target rules for targets named testa_pilha_coverage

# Build rule for target.
testa_pilha_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testa_pilha_coverage
.PHONY : testa_pilha_coverage

# fast build rule for target.
testa_pilha_coverage/fast:
	$(MAKE) -f CMakeFiles/testa_pilha_coverage.dir/build.make CMakeFiles/testa_pilha_coverage.dir/build
.PHONY : testa_pilha_coverage/fast

#=============================================================================
# Target rules for targets named pilha_vetor

# Build rule for target.
pilha_vetor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilha_vetor
.PHONY : pilha_vetor

# fast build rule for target.
pilha_vetor/fast:
	$(MAKE) -f pilha_vetor/CMakeFiles/pilha_vetor.dir/build.make pilha_vetor/CMakeFiles/pilha_vetor.dir/build
.PHONY : pilha_vetor/fast

testa_pilha.o: testa_pilha.cpp.o
.PHONY : testa_pilha.o

# target to build an object file
testa_pilha.cpp.o:
	$(MAKE) -f CMakeFiles/testa_pilha.dir/build.make CMakeFiles/testa_pilha.dir/testa_pilha.cpp.o
.PHONY : testa_pilha.cpp.o

testa_pilha.i: testa_pilha.cpp.i
.PHONY : testa_pilha.i

# target to preprocess a source file
testa_pilha.cpp.i:
	$(MAKE) -f CMakeFiles/testa_pilha.dir/build.make CMakeFiles/testa_pilha.dir/testa_pilha.cpp.i
.PHONY : testa_pilha.cpp.i

testa_pilha.s: testa_pilha.cpp.s
.PHONY : testa_pilha.s

# target to generate assembly for a file
testa_pilha.cpp.s:
	$(MAKE) -f CMakeFiles/testa_pilha.dir/build.make CMakeFiles/testa_pilha.dir/testa_pilha.cpp.s
.PHONY : testa_pilha.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... testa_pilha"
	@echo "... testa_pilha_coverage"
	@echo "... pilha_vetor"
	@echo "... testa_pilha.o"
	@echo "... testa_pilha.i"
	@echo "... testa_pilha.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

